language: python
services:
    - mysql
before_install:
    - mysql -u root < tests/create_database.sql 
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install bs4 
  - pip install mysql-connector
  - pip install pydfs-lineup-optimizer
script: 
  pytest --cov=MLB_Engine tests/;
after_success:
  - coveralls
